---
abstract: 'Alt. exporter w/persistent, dflts & auto ISA'
author:
  - 'LA Walsh (LAWALSH@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
  P: v1.1.17
  Test::Simple: 0.44
  mem: v0.4.2
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Xporter
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.0.7
